package org.bg52.artifacts.listener;

import org.bg52.artifacts.util.VersionUtil;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.entity.Entity;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.entity.EntityDeathEvent;
import org.bukkit.event.entity.ItemSpawnEvent;
import org.bukkit.event.inventory.InventoryOpenEvent;
import org.bukkit.event.inventory.InventoryType;
import org.bukkit.event.inventory.PrepareItemCraftEvent;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;

/**
 * Tags all naturally occurring slimeballs with a custom model data and item
 * model
 * so the resource pack can distinguish "real" slimeballs from the mimic model
 * item.
 *
 * Listens to:
 * - EntityDeathEvent (non-mimic entities dropping slimeballs)
 * - PrepareItemCraftEvent (crafted slimeballs in the result slot)
 * - InventoryOpenEvent (loot table generated slimeballs caught lazily for 1.14
 * support)
 * - ItemSpawnEvent (any slimeball item spawning in the world)
 */
public class SlimeballListener implements Listener {

    private static final int REAL_SLIMEBALL_CMD = 1;
    private static final String REAL_SLIMEBALL_MODEL_KEY = "real_slime_ball";

    // Reflection cache for setItemModel
    private static java.lang.reflect.Method setItemModelMethod = null;
    private static boolean setItemModelMethodChecked = false;

    /**
     * Tag slimeballs dropped by non-mimic entity deaths.
     */
    @EventHandler(priority = EventPriority.NORMAL)
    public void onEntityDeath(EntityDeathEvent event) {
        Entity entity = event.getEntity();

        // Skip mimic slimes — they have their own drop logic
        NamespacedKey mimicKey = new NamespacedKey("artifacts", "mimic");
        if (entity.getPersistentDataContainer().has(mimicKey,
                org.bukkit.persistence.PersistentDataType.BYTE)) {
            return;
        }

        for (ItemStack drop : event.getDrops()) {
            tagIfSlimeball(drop);
        }
    }

    /**
     * Tag slimeballs in crafting result slots.
     */
    @EventHandler(priority = EventPriority.NORMAL)
    public void onPrepareCraft(PrepareItemCraftEvent event) {
        ItemStack result = event.getInventory().getResult();
        if (result != null && result.getType() == Material.SLIME_BALL) {
            ItemStack tagged = tagSlimeball(result.clone());
            event.getInventory().setResult(tagged);
        }
    }

    /**
     * Tag slimeballs generated by loot tables lazily when chests are opened.
     * This replaces LootGenerateEvent to ensure 1.14 compatibility.
     */
    @EventHandler(priority = EventPriority.NORMAL)
    public void onInventoryOpen(InventoryOpenEvent event) {
        Inventory inventory = event.getInventory();
        InventoryType type = inventory.getType();

        // Only scan standard loot-holding containers to save performance
        if (type == InventoryType.CHEST || type == InventoryType.BARREL || type == InventoryType.SHULKER_BOX) {
            for (ItemStack item : inventory.getContents()) {
                tagIfSlimeball(item);
            }
        }
    }

    /**
     * Tag any slimeball item entity that spawns in the world.
     * This is the catch-all — covers drops, dispensers, broken chests, and any
     * other source.
     */
    @EventHandler(priority = EventPriority.NORMAL)
    public void onItemSpawn(ItemSpawnEvent event) {
        ItemStack item = event.getEntity().getItemStack();
        if (item.getType() == Material.SLIME_BALL) {
            ItemStack tagged = tagSlimeball(item);
            event.getEntity().setItemStack(tagged);
        }
    }

    /**
     * Tag an ItemStack if it's a slimeball (in-place modification).
     */
    private void tagIfSlimeball(ItemStack item) {
        if (item != null && item.getType() == Material.SLIME_BALL) {
            tagSlimeball(item);
        }
    }

    /**
     * Apply the real slimeball custom model data and item model to an ItemStack.
     * Sets both CustomModelData and ItemModel (on 1.21.3+) for maximum
     * compatibility.
     *
     * @return the same ItemStack, modified
     */
    @SuppressWarnings("deprecation")
    private ItemStack tagSlimeball(ItemStack item) {
        ItemMeta meta = item.getItemMeta();
        if (meta == null)
            return item;

        // Always set CustomModelData for older pack compatibility
        meta.setCustomModelData(REAL_SLIMEBALL_CMD);

        // Also set item model on 1.21.3+
        if (VersionUtil.supportsItemModel()) {
            try {
                if (!setItemModelMethodChecked) {
                    setItemModelMethodChecked = true;
                    Class<?> itemMetaClass = Class.forName("org.bukkit.inventory.meta.ItemMeta");
                    setItemModelMethod = itemMetaClass.getMethod("setItemModel", NamespacedKey.class);
                }
                if (setItemModelMethod != null) {
                    NamespacedKey key = new NamespacedKey("artifacts", REAL_SLIMEBALL_MODEL_KEY);
                    setItemModelMethod.invoke(meta, key);
                }
            } catch (Exception ignored) {
                // Silently fall back to CustomModelData only
            }
        }

        item.setItemMeta(meta);
        return item;
    }
}